apiVersion: batch/v1
kind: Job
metadata:
  name: kube-vip-setup
  namespace: kube-system
spec:
  template:
    spec:
      restartPolicy: Never
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
        - key: node.kubernetes.io/not-ready
          operator: "Exists"
          effect: NoSchedule
        - key: node.kubernetes.io/not-ready
          operator: "Exists"
          effect: NoExecute
      containers:
      - name: kube-vip-installer
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
          - |
            INTERFACE=$(ip route | awk '/default/ {print $5}')
            echo "Using interface: $INTERFACE"
            cat <<EOF > /etc/kubernetes/manifests/kube-vip.yaml
            apiVersion: v1
            kind: Pod
            metadata:
              name: kube-vip
              namespace: kube-system
            spec:
              containers:
              - args:
                - manager
                env:
                - name: vip_arp
                  value: "true"
                - name: port
                  value: "6443"
                - name: vip_interface
                  value: $INTERFACE
                - name: vip_cidr
                  value: "32"
                - name: cp_enable
                  value: "true"
                - name: cp_namespace
                  value: kube-system
                - name: vip_ddns
                  value: "false"
                - name: vip_leaderelection
                  value: "true"
                - name: vip_leaseduration
                  value: "5"
                - name: vip_renewdeadline
                  value: "3"
                - name: vip_retryperiod
                  value: "1"
                - name: address
                  value: 172.18.99.254
                - name: prometheus_server
                  value: :2112
                image: ghcr.io/kube-vip/kube-vip:v0.5.0
                imagePullPolicy: Always
                name: kube-vip
                securityContext:
                  capabilities:
                    add:
                    - NET_ADMIN
                    - NET_RAW
                volumeMounts:
                - mountPath: /etc/kubernetes/admin.conf
                  name: kubeconfig
              hostAliases:
              - hostnames:
                - kubernetes
                ip: 127.0.0.1
              hostNetwork: true
              volumes:
              - hostPath:
                  path: /etc/kubernetes/admin.conf
                name: kubeconfig
            EOF
        volumeMounts:
          - mountPath: /etc/kubernetes/manifests
            name: kube-manifests
      volumes:
        - name: kube-manifests
          hostPath:
            path: /etc/kubernetes/manifests
            type: Directory